# name of the software
name: Figure.NZ Guide
# current version of the software
version: 0.1.0
# url of the download button
downloadUrl: https://figure.nz
# licence of the software
license: MIT License
licenseUrl: http://opensource.org/licenses/MIT

# list of additional links on the right of the top menu
headerLinks:
  - title: Figure.NZ
    url: https://figure.nz

# list if additional links on the footer
footerLinks:
  - title: GitHub
    url: https://github.com/natdudley/theguide
  - title: Issues
    url: https://github.com/natdudley/theguide/issues?state=open

# header
header:
  color1: "#5E75F0"
  color2: "#3D506E"
  trianglify: true

# google analytics
analytics:
  account:
  domain:

# github buttons
githubButton:
  user: wikinewzealand
  repo: Guide

# twitter buttons
twitter:
  enabled: true
  via:
  hash:
  account:

# facebook buttons
facebook:
  enabled: true
  profileUrl:


exclude: ['README.md', 'LICENSE', 'bower.json', 'Gemfile.lock', 'Gemfile']

gems:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
